{% set name = "fcmaes" %}
{% set version = "1.2.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6da00809bedd7fc0c0dce67eef1369550595f8085216f2ca85e1b04d7bbe321

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - fcmaes

about:
  home: https://github.com/dietmarwo/fast-cma-es
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3 gradient-free optimization library.
  dev_url: https://github.com/dietmarwo/fast-cma-es

extra:
  recipe-maintainers:
    - oblute
    - mxr-conda
