{% set name = "fcmaes" %}
{% set version = "1.3.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fcmaes-{{ version }}.tar.gz
  sha256: 053eefbba915f4386d6eaaa34e90a5dcdaa8dd47c562484cf0267e1bb49b05df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - fcmaes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dietmarwo/fast-cma-es
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3 gradient-free optimization library.
  dev_url: https://github.com/dietmarwo/fast-cma-es

extra:
  recipe-maintainers:
    - mxr-conda
